main = ".open-next/worker.js"
name = "my-app"
compatibility_date = "2025-03-25"
compatibility_flags = ["nodejs_compat"]

[vars]
NEXT_PUBLIC_API_URL = ""
NEXT_PUBLIC_DISCORD_WEBHOOK_URL=""

[assets]
directory = ".open-next/assets"
binding = "ASSETS"